'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Command
    Public Property Id As Long
    Public Property Keyword As String
    Public Property Enabled As Boolean
    Public Property GlobalCD As Long
    Public Property UserCD As Long
    Public Property MinPermissionLevel As Long
    Public Property ExtraPrecondition As String
    Public Property CoolDownMessage As String
    Public Property Actions As String

End Class
