'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DatabaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DatabaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Commands() As DbSet(Of Command)
    Public Overridable Property Cooldowns() As DbSet(Of Cooldown)
    Public Overridable Property Timers() As DbSet(Of Timer)
    Public Overridable Property UserAttributes() As DbSet(Of UserAttribute)
    Public Overridable Property Users() As DbSet(Of User)

End Class
