'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Timer
    Public Property Name As String
    Public Property Enabled As Boolean
    Public Property Repeat As Long
    Public Property RepeatSeconds As Long
    Public Property NextTrigger As Date
    Public Property Action As String

End Class
