'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserName As String
    Public Property FirstSeen As Date
    Public Property FirstSeenThisSession As Date
    Public Property LastSeen As Date
    Public Property PermissionLevel As Long

End Class
